threads: 30
java_mem: 128
adapters: /pic/projects/mint/atlas_databases/adapters.fa
phix: /pic/projects/mint/atlas_databases/phiX174_virus.fa
rRNA: /pic/projects/mint/atlas_databases/silva_rfam_all_rRNAs.fa
kaijudb: /pic/projects/mint/metaomics/references/kaiju_nr_euk_viral
diamonddb: /pic/projects/mint/metaomics/references/kegg_feukaryotes_gprokaryotes.faa
gene2ko: /pic/projects/mint/metaomics/references/genes_ko.list.gz
kodefs: /pic/projects/mint/metaomics/references/20180419_ko_list.txt
samples:
  t1660m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1660mBot_S022_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1660mBot_S022_R2_001.fastq.gz
  t15104m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t15104mBot_S031_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t15104mBot_S031_R2_001.fastq.gz
  t14-104m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t14-104mBot_S017_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t14-104mBot_S017_R2_001.fastq.gz
  t164m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t164mBot_S020_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t164mBot_S020_R2_001.fastq.gz
  t1624m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1624mBot_S024_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1624mBot_S024_R2_001.fastq.gz
  t1532m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1532mBot_S023_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1532mBot_S023_R2_001.fastq.gz
  t1684m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1684mBot_S019_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1684mBot_S019_R2_001.fastq.gz
  t14100m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t14100mBot_S030_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t14100mBot_S030_R2_001.fastq.gz
  t140m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t140mBot_S016_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t140mBot_S016_R2_001.fastq.gz
  t1632m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1632mBot_S012_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1632mBot_S012_R2_001.fastq.gz
  t1720m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1720mBot_S033_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1720mBot_S033_R2_001.fastq.gz
  t1444m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1444mBot_S032_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1444mBot_S032_R2_001.fastq.gz
  t1760m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1760mBot_S028_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1760mBot_S028_R2_001.fastq.gz
  t1644m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1644mBot_S01_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1644mBot_S01_R2_001.fastq.gz
  t16104m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t16104mBot_S021_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t16104mBot_S021_R2_001.fastq.gz
  t1560m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1560mBot_S025_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1560mBot_S025_R2_001.fastq.gz
  t1464m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1464mBot_S07_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1464mBot_S07_R2_001.fastq.gz
  t1692m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1692mBot_S026_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1692mBot_S026_R2_001.fastq.gz
  t1612m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1612mBot_S014_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1612mBot_S014_R2_001.fastq.gz
  t1480m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1480mBot_S03_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1480mBot_S03_R2_001.fastq.gz
  t16100m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t16100mBot_S09_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t16100mBot_S09_R2_001.fastq.gz
  t174m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t174mBot_S011_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t174mBot_S011_R2_001.fastq.gz
  t1552m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1552mBot_S027_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1552mBot_S027_R2_001.fastq.gz
  t1424m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1424mBot_S08_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1424mBot_S08_R2_001.fastq.gz
  t1484m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1484mBot_S015_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1484mBot_S015_R2_001.fastq.gz
  t1764m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1764mBot_S05_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1764mBot_S05_R2_001.fastq.gz
  t1472m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1472mBot_S02_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1472mBot_S02_R2_001.fastq.gz
  t1592m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1592mBot_S010_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1592mBot_S010_R2_001.fastq.gz
  t1492m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1492mBot_S04_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1492mBot_S04_R2_001.fastq.gz
  t1752m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1752mBot_S018_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1752mBot_S018_R2_001.fastq.gz
  t1732m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1732mBot_S06_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1732mBot_S06_R2_001.fastq.gz
  t1460m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1460mBot_S029_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1460mBot_S029_R2_001.fastq.gz
  t1580m:
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1580mBot_S013_R1_001.fastq.gz
    - /pic/projects/mint/metaomics/raw/permafrost_incubations/t1580mBot_S013_R2_001.fastq.gz
