# the location of pair-end FASTQ files to annotate
data: tests/data
# individual process threads
threads: 8
# specify a number that represents GBs of available RAM
java_mem: 16
# number of reads to subsample by; 0 to disable
subsample: 60000
# adapter trimming occurs after successful sequence merge
adapters: resources/adapters.fa
contaminant_references:
    PhiX: resources/phix.fa
    rRNA: resources/rrna.fa.gz
# contains kaiju_db.fmi, nodes.dmp, and names.dmp
# makeDB.sh -e
kaijudb: tests/refdata
# curl ftp://ftp.expasy.org/databases/enzyme/enzyme.dat | gzip > enzyme.dat.gz
enzyme_dat_file: resources/enzyme.dat.gz
# curl ftp://ftp.expasy.org/databases/enzyme/enzclass.txt | gzip > enzclass.txt.gz
ec_converter: resources/enzclass.txt.gz
# process documented in resources/build_hmms.ipynb
hamap_hmm: resources/HAMAP-ACC.hmm
dbcan_hmm: resources/dbCAN-HMMdb-V7-ACC.hmm
