channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python=3.6
    - bbmap=37.99
    - click=6.7
    - diamond=0.9.21
    - kaiju=1.6.2
    - numpy
    - pandas=0.23.1
    - plotly=2.7.0
    - snakemake>=5.1.3
    - vsearch=2.6.0
    - pip
    - pip:
      - relatively
      - plotly>=3.0
