channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python=3.6
    - bbmap=37.99
    - click=6.7
    - diamond=0.9.22
    - hmmer=3.2.1
    - kaiju=1.6.2
    - krona=2.7
    - mmseqs2=6.f5a1c
    - numpy
    - pandas=0.23.4
    - snakemake>=5.1.3
    - vsearch=2.6.0
    - seqtk=1.3
    - pip
    - pip:
      - relatively
      - plotly>=3.0
